package com.bybit.api.client.restApi;

import com.bybit.api.client.domain.earn.request.AddLiquidityRequest;
import com.bybit.api.client.domain.earn.request.AddMarginRequest;
import com.bybit.api.client.domain.earn.request.ClaimLiquidityInterestRequest;
import com.bybit.api.client.domain.earn.request.ModifyEarnPositionRequest;
import com.bybit.api.client.domain.earn.request.PlaceAdvanceEarnOrderRequest;
import com.bybit.api.client.domain.earn.request.PlaceEarnOrderRequest;
import com.bybit.api.client.domain.earn.request.PlaceFixedTermOrderRequest;
import com.bybit.api.client.domain.earn.request.PlaceRwaOrderRequest;
import com.bybit.api.client.domain.earn.request.PlaceTokenOrderRequest;
import com.bybit.api.client.domain.earn.request.PwmClaimRequest;
import com.bybit.api.client.domain.earn.request.PwmCreateCustomPlanRequest;
import com.bybit.api.client.domain.earn.request.PwmFundTransferRequest;
import com.bybit.api.client.domain.earn.request.PwmInstCreateFundRequest;
import com.bybit.api.client.domain.earn.request.PwmInstCreateInvestmentPlanRequest;
import com.bybit.api.client.domain.earn.request.PwmInstCreateSubAccountRequest;
import com.bybit.api.client.domain.earn.request.PwmInstManageInvestmentPlanRequest;
import com.bybit.api.client.domain.earn.request.PwmInstManageOrderRequest;
import com.bybit.api.client.domain.earn.request.PwmInstSettleProfitRequest;
import com.bybit.api.client.domain.earn.request.PwmInvestMoreRequest;
import com.bybit.api.client.domain.earn.request.PwmRedeemRequest;
import com.bybit.api.client.domain.earn.request.PwmSubscribeRequest;
import com.bybit.api.client.domain.earn.request.RedeemFixedTermRequest;
import com.bybit.api.client.domain.earn.request.ReinvestLiquidityRequest;
import com.bybit.api.client.domain.earn.request.RemoveLiquidityRequest;
import com.bybit.api.client.domain.earn.request.SetFixedTermAutoInvestRequest;

public interface BybitApiEarnRestClient {
    Object addLiquidity(AddLiquidityRequest addLiquidityRequest);
    Object addMargin(AddMarginRequest addMarginRequest);
    Object claimLiquidityInterest(ClaimLiquidityInterestRequest claimLiquidityInterestRequest);
    Object getAdvanceEarnOrder(String category, Long productId, String orderId, String orderLinkId, Long startTime, Long endTime, Integer limit, String cursor);
    Object getAdvanceEarnPosition(String category, Long productId, String coin, Integer limit, String cursor);
    Object getAdvanceEarnProduct(String category, String coin, String duration);
    Object getAdvanceEarnProductExtraInfo(String category, Long productId);
    Object getDoubleWinLeverage(Long productId, String initialPrice, String lowerPrice, String upperPrice);
    Object getEarnAprHistory(String category, String productId, Long startTime, Long endTime);
    Object getEarnHourlyYieldHistory(String category, String productId, Long startTime, Long endTime, Integer limit, String cursor);
    Object getEarnOrderHistory(String category, String orderId, String orderLinkId, String productId, Long startTime, Long endTime, Integer limit, String cursor);
    Object getEarnPosition(String category, String productId, String coin);
    Object getEarnProduct(String category, String coin);
    Object getEarnYieldHistory(String category, Long productId, Long startTime, Long endTime, Integer limit, String cursor);
    Object getFixedTermOrder(String orderType, String productId, String category, String orderId, Long startTime, Long endTime, Integer limit, String cursor);
    Object getFixedTermPosition(String productId, String category, String coin);
    Object getFixedTermProduct(String coin);
    Object getHoldToEarnProduct();
    Object getHoldToEarnYieldHistory(Long timeStart, Long timeEnd, Integer limit, String cursor);
    Object getLiquidityMiningLiquidationRecords(String baseCoin, String quoteCoin, Long startTime, Long endTime, Integer limit, String cursor);
    Object getLiquidityMiningOrders(String orderId, String orderLinkId, String productId, String orderType, String status, Long startTime, Long endTime, Integer limit, String cursor);
    Object getLiquidityMiningPositions(String productId, String baseCoin);
    Object getLiquidityMiningProducts(String baseCoin, String quoteCoin);
    Object getLiquidityMiningYieldRecords(String baseCoin, String quoteCoin, Long startTime, Long endTime, Integer limit, String cursor);
    Object getRwaNavChart(Long productId, Long startTime, Long endTime);
    Object getRwaOrderList(String orderId, String orderLinkId, String orderType, Long productId, Long startTime, Long endTime, Integer limit, String cursor);
    Object getRwaPositionList();
    Object getRwaProductList(String coin);
    Object getSmartLeverageRedeemEstAmountList(String category, String positionIds);
    Object getTokenDailyYield(String coin, Long startTime, Long endTime, String cursor, Integer limit);
    Object getTokenHistoricalApr(String coin, Long range);
    Object getTokenHourlyYield(String coin, Long startTime, Long endTime, String cursor, Integer limit);
    Object getTokenOrderList(String coin, String orderLinkId, String orderId, String orderType, Long startTime, Long endTime, String cursor, Integer limit);
    Object getTokenPosition(String coin);
    Object getTokenProduct(String coin);
    Object listEarnCoupons(String category);
    Object modifyEarnPosition(ModifyEarnPositionRequest modifyEarnPositionRequest);
    Object placeAdvanceEarnOrder(PlaceAdvanceEarnOrderRequest placeAdvanceEarnOrderRequest);
    Object placeEarnOrder(PlaceEarnOrderRequest placeEarnOrderRequest);
    Object placeFixedTermOrder(PlaceFixedTermOrderRequest placeFixedTermOrderRequest);
    Object placeRwaOrder(PlaceRwaOrderRequest placeRwaOrderRequest);
    Object placeTokenOrder(PlaceTokenOrderRequest placeTokenOrderRequest);
    Object pwmAssetTrend(String planId, Long startTime, Long endTime);
    Object pwmClaim(PwmClaimRequest pwmClaimRequest);
    Object pwmCreateCustomPlan(PwmCreateCustomPlanRequest pwmCreateCustomPlanRequest);
    Object pwmFundNav(String fundId, Long startTime, Long endTime);
    Object pwmFundTransfer(PwmFundTransferRequest pwmFundTransferRequest);
    Object pwmGetNewPlanDetail(String planId);
    Object pwmGetPlanDetail(String planId);
    Object pwmInstCreateFund(PwmInstCreateFundRequest pwmInstCreateFundRequest);
    Object pwmInstCreateInvestmentPlan(PwmInstCreateInvestmentPlanRequest pwmInstCreateInvestmentPlanRequest);
    Object pwmInstCreateSubAccount(PwmInstCreateSubAccountRequest pwmInstCreateSubAccountRequest);
    Object pwmInstGetInvestmentPlans(String planId, String status, String subscriptionUid, Integer limit, String cursor);
    Object pwmInstListFunds(String fundId, String coin, String status, Integer limit, String cursor);
    Object pwmInstListOrders(String fundId, String orderType, String status, Long startTime, Long endTime, Integer limit, String cursor);
    Object pwmInstManageInvestmentPlan(PwmInstManageInvestmentPlanRequest pwmInstManageInvestmentPlanRequest);
    Object pwmInstManageOrder(PwmInstManageOrderRequest pwmInstManageOrderRequest);
    Object pwmInstSettleProfit(PwmInstSettleProfitRequest pwmInstSettleProfitRequest);
    Object pwmInvestMore(PwmInvestMoreRequest pwmInvestMoreRequest);
    Object pwmListInvestmentPlans(String planId, String status, Integer limit, String cursor);
    Object pwmListOrder(String planId, String category, String type, String status, Long startTime, Long endTime, Integer limit, String cursor, String orderLinkId);
    Object pwmListProductCards();
    Object pwmQueryFundTransferResult(String transferId, Long fromUserId);
    Object pwmRedeem(PwmRedeemRequest pwmRedeemRequest);
    Object pwmSubscribe(PwmSubscribeRequest pwmSubscribeRequest);
    Object redeemFixedTerm(RedeemFixedTermRequest redeemFixedTermRequest);
    Object reinvestLiquidity(ReinvestLiquidityRequest reinvestLiquidityRequest);
    Object removeLiquidity(RemoveLiquidityRequest removeLiquidityRequest);
    Object setFixedTermAutoInvest(SetFixedTermAutoInvestRequest setFixedTermAutoInvestRequest);
}
